FROM ubuntu:22.04

RUN echo "===STARTING MY CHALLANGE===\n"
RUN apt-get update
RUN apt-get install -y vim
RUN apt-get install -y gcc
RUN apt-get install -y gdb
RUN apt-get install -y valgrind

CMD ["bash"]
